org: prixus1231
app: express-lambda
service: express-lambda

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

plugins:
  - serverless-offline